/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const Screen = {
  // Candidate Screens
  CANDIDATE_LOGIN: 'CANDIDATE_LOGIN',
  CANDIDATE_EXPLORE: 'CANDIDATE_EXPLORE',
  CANDIDATE_OFFER_DETAIL: 'CANDIDATE_OFFER_DETAIL',
  CANDIDATE_APPLY: 'CANDIDATE_APPLY',
  CANDIDATE_SUCCESS: 'CANDIDATE_SUCCESS',
  CANDIDATE_APPLICATIONS: 'CANDIDATE_APPLICATIONS',
  
  // RH/Recruiter Screens
  RH_LOGIN: 'RH_LOGIN',
  RH_DASHBOARD: 'RH_DASHBOARD',
  RH_APPLICATIONS: 'RH_APPLICATIONS',
  RH_OFFERS: 'RH_OFFERS',
  RH_APPLICATION_DETAIL: 'RH_APPLICATION_DETAIL',
};
